- include_tasks: setup.yml
  vars:
    id: "{{ item.key }}"
    user: "{{ item.value }}"
  tags:
    - user
    - setup
    - user-setup
  with_dict: "{{ users }}"

- include_tasks: ssh.yml
  vars:
    id: "{{ outer_item.key }}"
    user: "{{ outer_item.value }}"
  tags:
    - user
    - ssh
    - user-ssh
  with_dict: "{{ users }}"
  loop_control:
    loop_var: outer_item

- include_tasks: root.yml
  tags:
    - user
    - ssh
    - user-ssh
