postgresql_version: 11
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_ctype: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_service_enabled: false

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_databases:
  - name: forj
    owner: forj
    encoding: 'UTF-8'

postgresql_users:
  - name: forj
    pass: forj
    encrypted: yes

postgresql_user_privileges:
  - name: forj
    db: forj
    priv: "ALL"
