---
- import_tasks: Debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - pyenv
  
- import_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags:
    - pyenv


- import_tasks: install.yml
  become: true
  become_user: "{{ pyenv_owner }}"
  when: pyenv_env == "user"
  tags:
    - pyenv
  
- import_tasks: install.yml
  become: true
  when: pyenv_env == "system"
  tags:
    - pyenv

