- name: install ssh
  apt:
    name: ssh
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: ensure ssh is running
  systemd:
    name: "ssh"
    state: started
    enabled: true
