- name: Deploy forj
  become: true
  become_user: www-data
  hosts: front
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}"
    ansistrano_deploy_to: "{{ deploy.root_path }}"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:thoas/forj.git
    ansistrano_git_branch: master
    ansistrano_shared_paths: ["media"]
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/../roles/deploy/tasks/before-symlink.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/../roles/deploy/tasks/after-symlink.yml"

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
