- name: Deploy forj
  become: true
  become_user: www-data
  hosts: front
  vars:
    ansistrano_deploy_to: "/var/www/forj"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:thoas/forj.git
    ansistrano_git_branch: master
    ansistrano_shared_paths: ["media"]
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/../roles/deploy/tasks/my-before-symlink-tasks.yml"

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
