- name: Rollback forj
  hosts: all
  vars:
    ansistrano_deploy_to: "/var/www/forj"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/../roles/deploy/tasks/after-symlink.yml"
  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }
