- name: Configure systemd service
  template:
    src: etc/systemd/system/default.service.j2
    dest: "/etc/systemd/system/forj-web.service"

- name: Reload systemd
  command: systemctl daemon-reload
  become_user: root
  become: true

- name: Restart systemd service
  systemd:
    name: "forj-web"
    state: restarted
    daemon_reload: yes
    enabled: true
  become_user: root
  become: true
