- name: Configure forj nginx config
  template:
    src: "etc/nginx/sites-available/forj.j2"
    dest: "/etc/nginx/sites-available/forj"
  notify: reload nginx
  tags:
    forj-nginx-conf

- name: enable forj nginx site
  notify: reload nginx
  file:
    src: "/etc/nginx/sites-available/forj"
    dest: "/etc/nginx/sites-enabled/forj"
    state: link
    force: yes
  tags:
    forj-nginx-conf
